### ISSUE TITLE
Fetching data twice

### ISSUE THREAD

**Issue by jaapterwoerds** [councilofelders/opensignals#12]
In the part downloading ticker data from Yahoo, we're seem to be downloading data twice. I think the intention is do create a do while loop which isn't native to python, but we just discard the result of the first call.

```
  data = requests.get(url=url, params=params)
    while(retries > 0):
        retries -= 1
        try:
            data = requests.get(
                url=url,
                params=params,
                headers={'User-Agent': user_agent}
            )
            data_json = data.json()
            quotes = data_json["chart"]["result"][0]
```
https://github.com/councilofelders/opensignals/blob/d7ce97e1c5fb385211ee1c92b5947697e76d38e3/src/opensignals/data/yahoo.py#L206

**Comment by jrdi** [comment]
Closed by #14
