### ISSUE TITLE
Suggestion: Enable target to improve corr20 performance

### ISSUE THREAD

**Issue by hellno** [councilofelders/opensignals#2]
Hi @jrdi, thanks for starting this great project! 🎉

I wanted to suggest having an additional target or a parameter to pick how many days into the future the target is created.
The easiest use case would be to change the target to be +20 days instead of +6.
 
I'd love to contribute to ysignals, so if you point me to the right direction and function I'm happy to open a PR.

Thanks!
Cheers
hellno

**Comment by jrdi** [comment]
Hi @hellno, thank you and your suggestion is great!

Would be great if you open a PR with the changes! I didn't check the targets, supposing that it's just a matter of choosing the right column... I think you can directly pass the target you want to use to the `get_data` function in `src/ysignals/data/yahoo.py`. I guess that you should rename the `live_data` target to always have the same name.
